### ISSUE TITLE
Panic when call Client::join_chat, unwrap on None value.

### ISSUE THREAD

**Issue by RuofengX** [Lonami/grammers#286]
thread 'tokio-runtime-worker' panicked at ~/.cargo/git/checkouts/grammers-689e30b82f69dcd5/8997a2d/lib/grammers-client/src/client/chats.rs:823:54:
called `Option::unwrap()` on a `None` value

**Comment by RuofengX** [comment]
`try_to_input_channel()` seems return a None value.
https://github.com/Lonami/grammers/blob/6a3cdbe122f9e5d733bd61d38b3daa993d4613ce/lib/grammers-client/src/client/chats.rs#L842

**Comment by RuofengX** [comment]
The issue context is like
```
2024-11-06T05:15:58.572771Z TRACE grammers_session::message_box: trying to set channel state for 1297632782: 756    
2024-11-06T05:15:58.572780Z TRACE grammers_session::message_box: trying to set channel state for 1733775262: 5928    
2024-11-06T05:15:58.572790Z TRACE grammers_session::message_box: trying to set channel state for 1220393924: 75262    
2024-11-06T05:15:58.572800Z TRACE grammers_session::message_box: trying to set channel state for 1850035520: 487    
2024-11-06T05:15:58.572809Z TRACE grammers_session::message_box: trying to set channel state for 1530075240: 46780    
2024-11-06T05:15:58.572819Z TRACE grammers_session::message_box: trying to set channel state for 1815406965: 89430    
2024-11-06T05:15:58.572828Z TRACE grammers_session::message_box: trying to set channel state for 1448906706: 44847    
2024-11-06T05:15:58.572838Z TRACE grammers_session::message_box: trying to set channel state for 1915313029: 1209    
2024-11-06T05:15:58.572848Z TRACE grammers_session::message_box: trying to set channel state for 1660720149: 3935533    
2024-11-06T05:15:58.572857Z TRACE grammers_session::message_box: trying to set channel state for 1793339741: 54873    
2024-11-06T05:15:58.572867Z TRACE grammers_session::message_box: trying to set channel state for 1670947842: 100    
2024-11-06T05:15:58.572877Z TRACE grammers_session::message_box: trying to set channel state for 1945226036: 176    
2024-11-06T05:15:58.572886Z TRACE grammers_session::message_box: trying to set channel state for 1515532031: 68    
2024-11-06T05:15:58.572896Z TRACE grammers_session::message_box: trying to set channel state for 1815560231: 208600    
2024-11-06T05:15:58.572905Z TRACE grammers_session::message_box: trying to set channel state for 1894160486: 14888    
2024-11-06T05:15:58.572915Z TRACE grammers_session::message_box: trying to set channel state for 1872194258: 54839    
2024-11-06T05:15:58.572924Z TRACE grammers_session::message_box: trying to set channel state for 1867213061: 76    
2024-11-06T05:15:58.572934Z TRACE grammers_session::message_box: trying to set channel state for 1556959524: 286    
2024-11-06T05:15:58.572943Z TRACE grammers_session::message_box: trying to set channel state for 1447754445: 1993    
2024-11-06T05:15:58.572953Z TRACE grammers_session::message_box: trying to set channel state for 1381485906: 64571    
thread 'tokio-runtime-worker' panicked at /home/ruofeng/.cargo/git/checkouts/grammers-689e30b82f69dcd5/6a3cdbe/lib/grammers-client/src/client/chats.rs:842:54:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by RuofengX** [comment]
It can confirmed that this issue surely happens when provide a id of a quited chat with a user(or bot) to `join_chat` function.

**Comment by RuofengX** [comment]
Join group also have same issue. Join channel is ok for now.

I am using cached packed chat to join a group/bot, is that the reason? Or does packed chat data became invalid after quit?

**Comment by Lonami** [comment]
Only public channels can be joined with this request, but it's true the library should not panic.

Packed chats are only valid in the session that acquired them. Logging in to the same account is considered a new session. But the panic here is trying to join something other than a channel.
